### ISSUE TITLE
I'm not sure what the vf value is supposed to be

### ISSUE THREAD

**Issue by aMartin6** [aMartin6/Final_Project#2]
In the text, the vf value is the coefficient that relates friction to velocity of the blocks. Changing it doesn't seem to affect the output at all, so I can't even find a ballpark of what it's supposed to be.

**Comment by mcddanielle** [comment]
Earlier when I sent the email, I should have used this.  I believe the original paper uses v_f=1.0
[PhysRevLett.62.2632.pdf](https://github.com/aMartin6/Final_Project/files/1944912/PhysRevLett.62.2632.pdf)
